### ISSUE TITLE
I want to encapsulate a component whose custom properties receive a function

### ISSUE THREAD

**Issue by zancheng** [mdn/web-components-examples#23]
I want to encapsulate a component whose custom properties receive a successful callback function. What can I do to meet this requirement?

```html
<user-card
    onChangeName="changeName()"
>
</user-card>
```
```javascript
function changeName() {
    ...
}
```
Like the code above.
How do I get the changeName method in a custom element?

**Comment by chrisdavidmills** [comment]
I think this depends on where the name to be changed would be recorded; how it would be changed. For example, if your custom element had a name attribute that would be changed, you could respond to it using the lifecycle callbacks, as explained in https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#Using_the_lifecycle_callbacks.

Or if your custom element used a template containing a slot that would have the name in, and it was editable, you could listen for the slot being changed. See https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots for basic slots explanation, and https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event for the relevant event to listen for.

**Comment by zancheng** [comment]
Thank you very much. I used custom attributes plus "eval ()" to fulfill my requirements.
```html
...
<user-card
    onChangeName="changeName"
>
</user-card>
...
```
```javascript
...
this.addEventListener('changeNameCallback', eval(changeNameCallback));
...
```
