### ISSUE TITLE
Falsy comment in the word-count-web-component javascript file.

### ISSUE THREAD

**Issue by Vaatik** [mdn/web-components-examples#51]
In the word-count-web-component javascript file, there is a comment that goes as follows :

```js
// Update count when element content changes
    setInterval(function() {
      var count = 'Words: ' + countWords(wcParent);
      text.textContent = count;
    }, 200) 
```

This comments proves to be falsy, because the code running under it does not apply the new word count "when" the content changes. It applies the new word count every 200 milliseconds. 

To make the code reflect the comment in a more truthful way, the code should instead listen for the input event on the parent node (the article itself) since the whole article is made editable via the contenteditable attribute in the html file.

it should go like this instead : 

```js
// Update count when element content changes
this.parentNode.addEventListener('input', () => {
      var count = 'Words: ' + countWords(wcParent);
      text.textContent = count;
    });
```

This way, the code respects the comment more and performance is also better (even if this is a small demo, those principles should be important to always consider. Even more, since this is MDN and MDN is a reference for alot of dev coming from alot of ranges of experience)

**Comment by MiB-1** [comment]
Hi @caugner  and @bsmth , I have raised PR for this #80 .
