### ISSUE TITLE
this.getAttribute("text") can get attrubute;

### ISSUE THREAD

**Issue by xiongwenlin** [mdn/web-components-examples#7]
console.log(this.this.getAttribute("text")  show null 
i use chrome;

**Comment by chrisdavidmills** [comment]
Hrm, I am confused, as I am sure I answered this a couple of days ago ;-)

* To start with, you have got `this.this` in the above line of code; it should be `this`, surely?
* Second, you are trying to get an attribute named "text". Does the custom element in question have an attribute named "text"?

Which example were you looking at

**Comment by xiongwenlin** [comment]
Thanks, i am sorry i make a mistake.
I'm looking at this .
https://github.com/mdn/web-components-examples/blob/master/popup-info-box-web-component/main.js

**Comment by chrisdavidmills** [comment]
No problem. The `getAttribute` line seems to return the text content for me as expected (I tried it in Chrome and Firefox).

What I did do was to change the `text` attribute to a proper `data-text` (`data-`) attribute, which is what I meant to do originally!
