### ISSUE TITLE
Please Make sure my Copyrights are not working open sourced. My Internet is not free.

### ISSUE THREAD

**Issue by Drewdaddy563677** [mdn/web-components-examples#75]
When I helped Mark Zuckerberg create Facebook by allowing him to open source my Copyrights of Apache 2.0 I agreed with it being free for customers of Facebook, but not companies using it as well . So there went a ton of money..I could be charging anyone and everyone for using my Copyrights and sending out invoices getting paid. Well if we can change changes to that way we can all expect a great price split

**Comment by ralyodio** [comment]
what are you on about??

**Comment by ralyodio** [comment]
damn i thought we were gonna have an MDN vs. Mark Zuckerberg lawsuit in the making lol
