### ISSUE TITLE
this.shadowRoot is not defined

### ISSUE THREAD

**Issue by SakshiShreya** [mdn/web-components-examples#76]
https://github.com/mdn/web-components-examples/blob/712ce27cd5b3c894ebc9b9958ec0973e3e86157b/slotchange/main.js#L40

`this.shadowRoot`
Remove `this.` as `this.shadowRoot` is null and `shadowRoot` is already defined

**Comment by SakshiShreya** [comment]
Can I please work on this.

**Comment by bsmth** [comment]
Thanks for reporting. @pepelsbey worked on this one recently, and I believe it worked then. Could you share some info about the browser version you're trying this on?

**Comment by pepelsbey** [comment]
Closing for now. Let me know if it's still relevant. Thanks!
